#!/bin/bash
WEATHER=$(curl -s v2.wttr.in | awk '/Weather:/ {gsub(",", " "); print $2 " " $3 " " $4 " " $5}') # & sleep 3s ; kill $!)
[ -n "$(printf "$WEATHER" | grep "Sunny")" ] && printf "\x09$WEATHER\x01\n" || printf "$WEATHER\n"
