#!/bin/sh
[ $(pgrep music) ] 2> /dev/null && exit 0

trim_quotes() {
	set -f
	old_ifs=$IFS
	IFS=\"
	set -- $1
	IFS=
	printf '%s\n' "$*"
	IFS=$old_ifs
	set +f
}

ICON_PAUSE=''
ICON_PLAY=''
PAUSE="$(trim_quotes "$(printf "{ \"command\": [\"get_property_string\", \"pause\"] }\n"\
	| socat - /tmp/mpvsocket 2> /dev/null | jq ".data")")"
TITLE="$(trim_quotes "$(printf "{ \"command\": [\"get_property\", \"filtered-metadata\"] }\n"\
	| socat - /tmp/mpvsocket 2> /dev/null | jq ".data.Title")")"

[ "$TITLE" = "null" ]
	TITLE="$(yt-dlp --skip-download --get-title "$(trim_quotes\
	"$(printf "{ \"command\": [\"get_property\", \"path\"] }\n"\
	| socat - /tmp/mpvsocket 2> /dev/null | jq ".data")")" 2> /dev/null)"

if [ "$PAUSE" = "yes" ]; then
	printf '%s %s\n' "$ICON_PAUSE" "$TITLE"
elif [ "$PAUSE" = "no" ]; then
	printf '%s %s\n' "$ICON_PLAY" "$TITLE"
fi
