#!/bin/sh
ICON=''
H="$(date '+%H')"
M="$(date '+%M')"

case $H in
2[2-3]|00)
	printf '\05%s %s:%s\01\n' "$ICON" "$H" "$M" ;;
0[1-6])
	printf '\06%s %s:%s\01\n' "$ICON" "$H" "$M" ;;
*)
	printf '%s %s:%s\n' "$ICON" "$H" "$M" ;;
esac
