#!/bin/sh
# I cba rewrite this one
WEATHER="$(curl -s v2.wttr.in | awk '/Weather:/ {gsub(",", " "); print $2 " " $4 " " $5}')"
ICON="$(printf "$WEATHER" | awk '{print $1}')"
TEMP1="$(printf "$WEATHER" | awk '{print $2}')"
TEMP2="$(printf "$WEATHER" | awk '{print $3}')"

case "$TEMP1" in
+*|-*)  printf "$ICON $TEMP1\n" ;;
*)      printf "$ICON $TEMP2\n" ;;
esac
