#!/bin/sh
WEATHER="$(curl -s v2.wttr.in)"
ICON="$(printf '%s\n' "$WEATHER" | awk '/Weather:/ {print $2}')"
TEMP="$(printf '%s\n' "$WEATHER" | sed -n -e 's/^.*Weather:.*+//p' | cut -f1 -d ,)"

[ -z "$TEMP" ] &&
	"$(printf '%s\n' "$WEATHER" | sed -n -e 's/^.*Weather:.*-//p' | cut -f1 -d ,)"

printf '%s %s\n' "$ICON" "$TEMP"
